document.write('<!--Table Declaration-->');
document.write('	<table id="wholetable" cellspacing="0">');
document.write('		<tbody>');
document.write('			<tr>');
document.write('<!--Header-->');
document.write('				<td colspan="2" id="maintitlebg">');
document.write('				<div id"maintitle"><a href="index.html"><img src="images/logo.png" alt="Magus Madhouse Zone" style="width:30%;height:30%;"></a></div>');
document.write('				</td>');
document.write('			</tr>');
document.write('<!--Nav-->');
document.write('		<tr>');
document.write('			<td id="breadcrumbs"><a href=images/7hnrspc766jz.webp>I&#39;m so pumped for autumn I&#39m gonna fill my ass with leaves</a></td>');
document.write('		</tr>');
document.write('<!--Main-->	');
document.write('	<tr>');
document.write('		<td class="maintdenc" colspan="2">');
document.write('			<table style="width:100%;">');
document.write('				<tbody>');
document.write('					<tr>');