document.write('<!--Table Declaration-->');
document.write('	<table id="wholetable" cellspacing="0">');
document.write('		<tbody>');
document.write('			<tr>');
document.write('<!--Header-->');
document.write('				<td colspan="2" id="maintitlebg">');
document.write('				<div id"maintitle"><a href="index.html"><img src="images/logo.png" alt="Magus Madhouse Zone" style="width:30%;height:30%;"></a></div>');
document.write('				</td>');
document.write('			</tr>');
document.write('<!--Nav-->');
document.write('		<tr>');
document.write('			<td id="breadcrumbs">Monmona 2024?</td>');
document.write('		</tr>');
document.write('<!--Main-->	');
document.write('	<tr>');
document.write('		<td class="maintdenc" colspan="2">');
document.write('			<table style="width:100%;">');
document.write('				<tbody>');
document.write('					<tr>');