document.write('<td class="maintdside" id=sidebar">');
document.write('	<table class="menu" id="menubar" border="0" cellpadding="2" cellspacing="0" width="90%">');
document.write('		<tbody>');
document.write('			<tr>');
document.write('				<th>');
document.write('					<div align="center" style="border: 1px solid #FFF;">');
document.write('					The Library');
document.write('					</div>');
document.write('				</th>');
document.write('			</tr>');
document.write('			<tr>');
document.write('				<td valign="top" nowrap>');
//document.write('				<a href="webcomics.html">Webcomics</a>');
//document.write('				<br>');
document.write('				<a href="games.html">Games</a>');
document.write('				<br>');
document.write('				<a href="illustrations.html">Illustrations</a>');
document.write('				<br>');
document.write('				<a href="podcasts.html">Podcasts</a>');
document.write('				</td>');
document.write('			</tr>');
document.write('		</tbody>');
document.write('	</table>');
document.write('<br>');
document.write('	<table class="menu" id="menubar" border="0" cellpadding="2" cellspacing="0" width="90%">');
document.write('		<tbody>');
document.write('			<tr>');
document.write('				<th style="border: 1px solid #FFF;">');
document.write('					<div align="center">');
document.write('					The Study');
document.write('					</div>');
document.write('				</th>');
document.write('			</tr>');
document.write('			<tr>');
document.write('				<td valign="top" nowrap>');
document.write('				<a href="aboutus.html">About Us</a>');
document.write('				<br>');
document.write('				<a href="characterinfo.html">Character Info</a>');
document.write('				<br>');
// document.write('				<a href="worldinfo.html">World Info</a>');
document.write('				<a href="downloads.html">Downloads</a>');
document.write('				<br>');
document.write('				<a href="blog.html">Blog</a>');
document.write('				</td>');
document.write('			</tr>');
document.write('		</tbody>');
document.write('	</table>');
document.write('<br>');
document.write('	<table class="menu" id="menubar" border="0" cellpadding="2" cellspacing="0" width="90%">');
document.write('		<tbody>');
document.write('			<tr>');
document.write('				<th style="border: 1px solid #FFF;">');
document.write('					<div align="center">');
document.write('					The Sitting Room');
document.write('					</div>');
document.write('				</th>');
document.write('			</tr>');
document.write('			<tr>');
document.write('				<td valign="top" nowrap>');
document.write('				<a href="https://www.linktr.ee/anpucamilla">&#x29c9; Social Media</a>');
document.write('				<br>');
document.write('				<a href="miscellany.html">Miscellany</a>');
document.write('				<br>');
document.write('				<a href="http://users3.smartgb.com/g/g.php?a=s&i=g36-33287-81">&#x29c9; Guestbook</a>');
document.write('				<br>');
// document.write('				<a href="donate.html">Donate</a>');
document.write('				</td>');
document.write('			</tr>');
document.write('		</tbody>');
document.write('	</table>');
document.write('</td>');
