document.write('<td class="maintdside" id=sidebar">');
document.write('	<table class="menu" id="menubar" border="0" cellpadding="2" cellspacing="0" width="90%">');
document.write('		<tbody>');
document.write('			<tr>');
document.write('				<th>');
document.write('					<div align="center" style="border: 1px solid #FFF;">');
document.write('					Quick Links');
document.write('					</div>');
document.write('				</th>');
document.write('			</tr>');
document.write('			<tr>');
document.write('				<td valign="top" nowrap>');
document.write('				<a href="https://anpucamilla.itch.io/peacefulpurgatory"><img src="images/peacefulbanner.png" alt="Peaceful Purgatory" title="Peaceful&Purgatory" width="130" height="50" border="0/"></a>');
document.write('				<br>');
document.write('				<a href="https://anpucamilla.itch.io/rhapsodyofcrosspollination"><img src="images/rhapsodybanner.png" alt="Tender Frame Cocoon: Rhapsody of Cross-Pollination" title="TENDER FRAME COCOON: //rhapsody of cross-pollination" width="130" height="50" border="0/"></a>');
document.write('				<br>');
document.write('				<a href="illus2023.html"><img src="images/illustrationbanner2023.png" alt="Latest Art" title="Latest Art" width="130" height="50" border="0/"></a>');
document.write('				<br>');
document.write('				</td>');
document.write('			</tr>');
document.write('		</tbody>');
document.write('	</table>');
document.write('<br>');
document.write('	<table class="menu" id="menubar" border="0" cellpadding="2" cellspacing="0" width="90%">');
document.write('		<tbody>');
document.write('			<tr>');
document.write('				<th>');
document.write('					<div align="center" style="border: 1px solid #FFF;">');
document.write('					Affiliates');
document.write('					</div>');
document.write('				</th>');
document.write('			</tr>');
document.write('			<tr>');
document.write('				<td valign="top" nowrap>');
document.write('				<a href="https://tin.zone/"><img src="images/tinzonebanner.png" alt="Tin Zone" title="Tin.zone" width="130" height="50" border="0/"></a>');
document.write('				<br>');
document.write('				</td>');
document.write('			</tr>');
document.write('		</tbody>');
document.write('	</table>');
document.write('</td>');
